[package]
name = "lapin-futures"
version = "0.19.0-beta2"
edition = "2018"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>", "Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
repository = "https://github.com/sozu-proxy/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapin-futures"
description = "AMQP client library with a futures based API"
keywords = ["amqp", "rabbitmq", "futures", "tokio"]
categories = ["database"]
license = "MIT"

[dependencies]
futures-preview = "=0.3.0-alpha.16"
log = "^0.4"
parking_lot = "^0.8"

[dependencies.lapin-async]
version = "=0.19.0-beta2"
path = "../async"

[dev-dependencies]
env_logger = "^0.6"
failure = "^0.1"
tokio = "^0.1.8"
